// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9yIp3d6WmL8ExF5BcdOrj9KO28dvyyUU',
    appId: '1:1092695787763:web:c9be841f3f0d92fde64f86',
    messagingSenderId: '1092695787763',
    projectId: 'animecoloring-50c15',
    authDomain: 'animecoloring-50c15.firebaseapp.com',
    storageBucket: 'animecoloring-50c15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaOwmgULGHjeMcWEWZuE6_Ad7RP0qEWpE',
    appId: '1:1092695787763:android:c0b97fa6341fedb5e64f86',
    messagingSenderId: '1092695787763',
    projectId: 'animecoloring-50c15',
    storageBucket: 'animecoloring-50c15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOmb6HPFGFAEZRY4eYh1IN1C7q48qxqw',
    appId: '1:1092695787763:ios:c93d5d18bba22542e64f86',
    messagingSenderId: '1092695787763',
    projectId: 'animecoloring-50c15',
    storageBucket: 'animecoloring-50c15.appspot.com',
    iosBundleId: 'com.example.animeAutoColoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOmb6HPFGFAEZRY4eYh1IN1C7q48qxqw',
    appId: '1:1092695787763:ios:1bb86356f392314ee64f86',
    messagingSenderId: '1092695787763',
    projectId: 'animecoloring-50c15',
    storageBucket: 'animecoloring-50c15.appspot.com',
    iosBundleId: 'com.example.animeAutoColoring.RunnerTests',
  );
}
